services:

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    networks:
      - gautham-network

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - gautham-network

  configserver:
    image: "gautham/configserver:s1"
    container_name: configserver
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_started
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - gautham-network

  eurekaserver:
    image: "gautham/eurekaserver:s1"
    container_name: eurekaserver
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_started
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    networks:
      - gautham-network

  accounts:
    image: "gautham/accounts:s1"
    container_name: accounts
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_PROFILES_ACTIVE: prod
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - gautham-network

  cards:
    image: "gautham/cards:s1"
    container_name: cards
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - gautham-network

  loans:
    image: "gautham/loans:s1"
    container_name: loans
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - gautham-network

  gatewayserver:
    image: "gautham/gatewayserver:s1"
    container_name: gatewayserver
    ports:
      - "8072:8072"
    depends_on:
      configserver:
        condition: service_started
      accounts:
        condition: service_started
      cards:
        condition: service_started
      loans:
        condition: service_started
      eurekaserver:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      OTEL_SERVICE_NAME: "gatewayserver"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - gautham-network
    deploy:
      resources:
        limits:
          memory: 700m

networks:
  gautham-network:
    driver: "bridge"